### ISSUE TITLE
Linux ARM64 binary releases

### ISSUE THREAD

**Issue by jalaziz** [anza-xyz/agave#2124] opened 2024-07-12 23:58 UTC
#### Problem

Today, there are only x86_64 releases for Linux. However, ARM releases are available for macOS (darwin). It would be great if Linux arm64 releases could be made available.

#### Proposed Solution

Add Linux arm64 builds to the release pipeline.

**Comment by dzmitry-lahoda** [comment] 2024-12-12 13:25
assuming duplicate of https://github.com/anza-xyz/agave/issues/1734

**Comment by joncinque** [comment] 2024-12-13 11:28
Correct, this is a duplicate, thanks!

**Closed as not planned by joncinque** 2024-12-13 11:28 UTC
Labels: community
