### ISSUE TITLE
The installer won't be downloaded on my system (404)

### ISSUE THREAD

**Issue by real-felix** [anza-xyz/agave#2524] opened 2024-08-09 09:46 UTC
#### Problem

When trying to install the CLI on my system (Linux ARM64), I get a 404

```
> sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
downloading stable installer
curl: (22) The requested URL returned error: 404
agave-install-init: command failed: downloader https://release.anza.xyz/stable/agave-install-init-aarch64-unknown-linux-gnu /tmp/tmp.BNcFE8ooRi/agave-install-init
```

#### Proposed Solution

Adding this arch to the CI? Not sure exactly how it works.

**Comment by heyAyushh** [comment] 2024-08-09 11:31
It isn't working for docker on MacOS M1 Pro

```Dockerfile
FROM ubuntu:22.04 
```

```
 => CANCELED [server build 4/4] RUN cargo build --release                                                                                                                   0.5s
------
 > [server stage-2 1/5] RUN sh -c "$(curl -sSfL https://release.anza.xyz/v1.18.17/install)":
0.185 downloading v1.18.17 installer
0.509 curl: (22) The requested URL returned error: 404
0.516 agave-install-init: command failed: downloader https://release.anza.xyz/v1.18.17/agave-install-init-aarch64-unknown-linux-gnu /tmp/tmp.ICXtI4gRyE/agave-install-init
```

**Comment by joncinque** [comment] 2024-08-10 12:05
If you look at a release page like https://github.com/anza-xyz/agave/releases/tag/v1.18.22, you'll notice that there are no aarch64 linux builds. Since this is a duplicate of https://github.com/anza-xyz/agave/issues/1734, I'll close this issue so it can be tracked over there

**Closed as not planned by joncinque** 2024-08-10 12:05 UTC
Labels: community
